# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.FloatField(),
        ),
    ]
