# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20180105_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='cloud',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
