# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20180402_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='clouds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
