# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crj',
            old_name='day',
            new_name='menu',
        ),
    ]
