# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-28 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171028_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='day',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='yangjin',
            old_name='day',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='yangsung',
            old_name='day',
            new_name='menu',
        ),
    ]
