# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_galaxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
