# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_haksa_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
