# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_notice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='haksa',
            name='notice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haksa',
            name='url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
