# Generated by Django 2.1.7 on 2019-05-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yangjin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yangsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
    ]
