# Generated by Django 2.1.7 on 2019-09-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralDorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('menu', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=50, verbose_name='유저식별키')),
                ('dorm', models.CharField(max_length=10, verbose_name='기숙사')),
            ],
        ),
        migrations.CreateModel(
            name='Yangjin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('menu', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yangsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('menu', models.TextField(max_length=200)),
            ],
        ),
    ]
